return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "actionlint",
      "buf",
      "cfn-lint",
      "colorgen-nvim",
      "commitlint",
      "cpplint",
      "cmakelang",
      "delve",
      "djlint",
      "elm-format",
      "erb-lint",
      "goimports",
      "golangci-lint",
      "golines",
      "hadolint",
      "isort",
      "jq",
      "mypy",
      "markdownlint",
      "prettier",
      "prettierd",
      "protolint",
      "rstcheck",
      -- "rubocop",
      "selene",
      "stylua",
      "shellcheck",
      "shfmt",
      "taplo",
      "texlab",
      "ty",
    },
  },
}
